Repository mattermost/mattermost-mattermod, pull requests merged in 2019-11, with the labels that each got.

#61 Only mark community contributions as stale
  server/pull_request.go
Labels: 3: Reviews Complete

#62 [IS-239] add auto merge PR feature
  config/config-mattermod.json
  mattermod.go
  server/auto_merge.go
  server/config.go
Labels: 2: Dev Review

#64 use vendor folder to build/test/lint
  Makefile
Labels: 3: Reviews Complete, AutoMerge

#63 add update branch command
  server/server.go
  server/update_branch.go
Labels: 3: Reviews Complete
