Repository mattermost/mattermost-mattermod, pull requests merged in 2019-08, with the labels that each got.

#39 [MM-17073] Mattermod Refactor #2
  cloud/installation.go
  cloud/models.go
  mattermod.go
  model/pull_request.go
  server/cherry_pick.go
  server/cla.go
  server/config.go
  server/github.go
  server/github_pr.go
  server/issue.go
  server/limit_rate_gh.go
  server/pull_request.go
  server/server.go
  server/spinmint.go
  server/spinwick.go
  server/spinwick_test.go
  server/utils.go
  server/webhook.go
Labels: 2: Dev Review

#40 uses new sizes for test servers
  server/pull_request.go
Labels: 3: Reviews Complete

#41 remove label when test server fail and do some comments cleanup
  server/github.go
  server/pull_request.go
  server/spinwick.go
Labels: 2: Dev Review

#42 add license when requesting a HA spinWick
  cloud/models.go
  config/config-mattermod.json
  server/config.go
  server/pull_request.go
  server/spinwick.go
Labels: 2: Dev Review, 3: Reviews Complete

#43 add sha in the update server message and remove old comments
  server/spinwick.go
Labels: 3: Reviews Complete

#44 fix upgrade installation when is in ha mode
  cloud/models.go
  server/pull_request.go
  server/spinwick.go
Labels: 2: Dev Review
