Repository mattermost/mattermost-mattermod, pull requests merged in 2019-10, with the labels that each got.

#56 Fix permission issues from PR/Forks triggering the circleci job with a org member
  config/config-mattermod.json
  go.mod
  go.sum
  model/pull_request.go
  server/circleci.go
  server/config.go
  server/github.go
  server/pull_request.go
  server/spinmint.go
  store/sql_pull_request_store.go
  vendor/github.com/cpanato/go-circleci/CHANGELOG.md
  vendor/github.com/cpanato/go-circleci/LICENSE
  vendor/github.com/cpanato/go-circleci/README.md
  vendor/github.com/cpanato/go-circleci/circleci.go
  vendor/modules.txt
Labels: 3: Reviews Complete

#57 Automatically add Hacktoberfest label to new community PRs
  model/pull_request.go
  server/community.go
  server/github.go
  server/pull_request.go
Labels: 2: Dev Review

#60 add ability to set a spinwick for other repositories
  server/spinwick.go
Labels: 2: Dev Review

#59 add merge pr block status when set a do not merge label
  config/config-mattermod.json
  server/block_pr_merge.go
  server/config.go
  server/pull_request.go
Labels: 3: Reviews Complete, Do Not Merge
