Repository mattermost/mattermost-mattermod, pull requests merged in 2020-06, with the labels that each got.

#137 Don't log org members
  server/server.go
Labels: 2: Dev Review

#138 Succeed CLA status for excluded user.
  server/cla.go
Labels: AutoMerge

#139 MM-26379: remove duplicate os.Interrupt signals
  .gitignore
  mattermod.go
Labels: 3: Reviews Complete

#142 MM-26419: make store methods synchronous
  server/auto_merge.go
  server/builds.go
  server/github.go
  server/issue.go
  server/pull_request.go
  server/spinmint.go
  store/sql_issue_store.go
  store/sql_pull_request_store.go
  store/sql_spinmint.store.go
  store/store.go
Labels: 3: Reviews Complete

#146 [MM26383] server/server_test: remove globals and slim down tests
  Makefile
  server/server.go
  server/server_test.go
Labels: 3: Reviews Complete

#147 [MM-26377] server/builds: remove unnecessary code
  server/builds.go
  server/builds_mocked.go
Labels: 3: Reviews Complete

#145 [MM-26418] Extract AWS Session creation
  server/server.go
  server/spinmint.go
Labels: 3: Reviews Complete

#148 [MM-26380] Replace manners with standard library shutdown
  mattermod.go
  server/cherry_pick.go
  server/server.go
Labels: 2: Dev Review
