Repository mattermost/mattermost-mattermod, pull requests merged in 2020-07, with the labels that each got.

#141 [MM-26417] Refactor use of context and add timeouts
  go.mod
  go.sum
  server/auto_merge.go
  server/autoassign.go
  server/block_pr_merge.go
  server/build_mobile_apps.go
  server/builds.go
  server/cherry_pick.go
  server/circleci.go
  server/cla.go
  server/community.go
  server/config.go
  server/enterprise.go
  server/github.go
  server/issue.go
  server/limit_rate_gh.go
  server/pull_request.go
  server/pull_request_test.go
  server/server.go
  server/spinmint.go
  server/update_branch.go
Labels: 3: Reviews Complete

#153 Upgrade github dependency to v32
  go.mod
  go.sum
  server/auto_merge.go
  server/autoassign.go
  server/block_pr_merge.go
  server/cherry_pick.go
  server/cla.go
  server/cla_test.go
  server/enterprise.go
  server/github.go
  server/github_client.go
  server/github_pr.go
  server/github_test.go
  server/mocks/checks.go
  server/mocks/git.go
  server/mocks/issues.go
  server/mocks/organizations.go
  server/mocks/pull_requests.go
  server/mocks/repositories.go
  server/pull_request.go
  server/pull_request_test.go
  server/server.go
  server/update_branch.go
Labels: 3: Reviews Complete

#151 [MM-26585] cmd: move main function into cmd directory
  Makefile
  cmd/mattermost-mattermod/main.go
Labels: 3: Reviews Complete

#150 [MM-26612] Include go mod tidy check
  .circleci/config.yml
Labels: 3: Reviews Complete

#143 Reimplement translation prs
  config/config-mattermod.default.json
  server/cla.go
  server/config.go
  server/enterprise.go
  server/github.go
  server/pull_request.go
  server/server.go
  server/spinmint.go
  server/testdata/schema/ping.schema.json
  server/translations.go
  server/utils.go
  server/webhook.go
  server/webhook_test.go
Labels: 2: Dev Review

#156 MM-26453: Add tests for auto_merge.go
  Makefile
  cmd/mattermost-mattermod/main.go
  server/auto_merge.go
  server/auto_merge_test.go
  server/mocks/checks.go
  server/mocks/git.go
  server/mocks/issues.go
  server/mocks/organizations.go
  server/mocks/pull_requests.go
  server/mocks/repositories.go
  server/pull_request.go
  store/mocks/issue.go
  store/mocks/pull_requests.go
  store/mocks/spinmint.go
  store/mocks/store.go
Labels: 3: Reviews Complete

#154 [MM-26580] server/update_branch: add some tests
  model/pull_request.go
  server/github.go
  server/pull_request.go
  server/server.go
  server/update_branch.go
  server/update_branch_test.go
Labels: 3: Reviews Complete

#158 [MM-26578] store/sql_pull_request_store: add tests
  store/sql_pull_request_store_test.go
  store/sql_store_test.go
Labels: 3: Reviews Complete

#155 [MM-26385] Include cache and rate limiter to GH client
  config/config-mattermod.default.json
  go.mod
  go.sum
  server/github_client.go
  server/github_test.go
  server/limit_rate_gh.go
  server/rate_limit.go
  server/server.go
Labels: 3: Reviews Complete

#164 [MM-26798] Fix automerge error with null columns
  model/pull_request.go
  server/github.go
  server/pull_request.go
  server/update_branch.go
  server/update_branch_test.go
  store/migrations/20200708181600_add_maintainercanmodify_column.sql
Labels: 2: Dev Review

#159 Translations: Fix PR URL
  server/translations.go
Labels: AutoMerge

#165 Allow other user to be the root
  store/sql_store_test.go
Labels: 3: Reviews Complete

#166 MM-26797: Fix context cancellation on goroutines
  server/cherry_pick.go
  server/cla.go
  server/pull_request.go
Labels: 2: Dev Review

#163 [MM-26579] store: add tests for spinmint store
  store/sql_spinmint_store.go
  store/sql_spinmint_store_test.go
Labels: 2: Dev Review

#161 [MM-26771] server: reduce code dupl. in handlers and add some error propogation
  model/pull_request.go
  server/autoassign.go
  server/cherry_pick.go
  server/cla.go
  server/github.go
  server/pull_request.go
  server/server.go
  store/migrations/20200709132700_add_merged_column.sql
  store/sql_pull_request_store.go
Labels: 3: Reviews Complete

#167 MM-26829: Fix duplicate label removal
  server/auto_merge.go
  server/pull_request.go
Labels: 3: Reviews Complete

#169 [MM-26454] Add tests for block_pr_merge
  server/block_pr_merge.go
  server/block_pr_merge_test.go
  server/pull_request.go
Labels: 3: Reviews Complete

#172 [MM-26577] Tests for Issue store
  store/sql_issue_store_test.go
Labels: 2: Dev Review

#168 [MM-26841] server: gently refactor github handler v1
  server/github_pr.go
  server/pull_request.go
  server/server.go
Labels: 3: Reviews Complete

#177 Containerize mattermod
  .circleci/config.yml
  Dockerfile
  Makefile
Labels: 2: Dev Review

#175 [MM-26819] server: add some error propogation to handleIssueEvent
  server/issue.go
  server/pull_request.go
  server/server.go
Labels: 3: Reviews Complete

#176 [MM-26815] server/pull_request: tweak auto merge label handling
  server/pull_request.go
Labels: 2: Dev Review

#174 [MM-26723] Metrics system
  Makefile
  cmd/mattermost-mattermod/main.go
  config/config-mattermod.default.json
  go.mod
  go.sum
  metrics/metrics_test.go
  metrics/mocks/provider.go
  metrics/provider.go
  metrics/server.go
  server/auto_merge.go
  server/auto_merge_test.go
  server/config.go
  server/github_client.go
  server/github_test.go
  server/metrics.go
  server/mocks/provider.go
  server/pull_request.go
  server/response_writer_wrapper.go
  server/response_writer_wrapper_test.go
  server/server.go
  server/server_test.go
  server/spinmint.go
Labels: 2: Dev Review

#179 MM-26927: Use a recovery middleware
  server/server.go
  server/server_test.go
Labels: 3: Reviews Complete

#180 Replacing blacklist with blocklist where is possible without braking the API
  server/circleci.go
Labels: 3: Reviews Complete

#181 Add .gitlab-ci configuration for deployment
  .gitlab-ci.yml
Labels: 2: Dev Review

#182 Add release targets and script
  Makefile
  hack/release.sh
Labels: 2: Dev Review

#171 MM-26756: cherry-pick instead of am
  hack/README.md
  hack/cherry-pick.sh
  model/pull_request.go
  server/cherry_pick.go
  server/github.go
Labels: 3: Reviews Complete

#178 Add k8s manifests and dev tooling
  .gitignore
  Makefile
  README.md
  Tiltfile
  deploy/base/app/deployment.yaml
  deploy/base/app/kustomization.yaml
  deploy/base/app/rbac.yaml
  deploy/base/app/service.yaml
  deploy/base/config/kustomization.yaml
  deploy/base/db/deployment.yaml
  deploy/base/db/kustomization.yaml
  deploy/base/db/pvc.yaml
  deploy/base/db/secrets.yaml
  deploy/base/db/service.yaml
  deploy/base/db/serviceaccount.yaml
  deploy/overlays/dev/kustomization.yaml
  deploy/overlays/dev/patches/service-nodeport.yaml
  deploy/overlays/prod/ingress.yaml
  deploy/overlays/prod/kustomization.yaml
  deploy/overlays/prod/patches/database-pvc.yaml
  deploy/overlays/prod/patches/deployment-replicas.yaml
  server/server.go
Labels: 2: Dev Review

#173 MM-26709 advanced logging for mattermod
  cmd/mattermost-mattermod/main.go
  go.mod
  go.sum
  server/config.go
  server/server.go
Labels: 3: Reviews Complete

#183 [MM-26929] server/github: replace selecotors with methods
  server/github.go
Labels: 2: Dev Review

#184 [MM-27175] server: add middleware for validation
  server/server.go
  server/server_test.go
  server/validate_signature.go
  server/validate_signature_test.go
Labels: 2: Dev Review

#187 Fix deploy
  Makefile
  cmd/mattermost-mattermod/main.go
Labels: 2: Dev Review

#188 add required fields to default config
  config/config-mattermod.default.json
Labels: 3: Reviews Complete

#194 MM-25272: Fix superfluous write header
  server/validate_signature.go
Labels: 3: Reviews Complete

#186 [MM-27017] server: add new endpoint for issues webhook
  server/github.go
  server/github_pr.go
  server/issue.go
  server/issue_handler.go
  server/issue_handler_test.go
  server/server.go
Labels: 2: Dev Review

#200 MM-27329: Fix incorrect error check
  server/server.go
Labels: 3: Reviews Complete

#201 Properly log the full panic trace
  server/server.go
Labels: 2: Dev Review

#202 Add proper git configuration for runtime
  .gitignore
  Dockerfile
  deploy/base/app/deployment.yaml
  deploy/overlays/prod/kustomization.yaml
  deploy/overlays/prod/patches/deployment-config.yaml
  deploy/overlays/prod/patches/deployment-gitconfig.yaml
Labels: 2: Dev Review

#199 Add steps to locally set up Mattermod
  README.md
Labels: 2: Dev Review

#204 MM-27189: Fix comment with empty body
  server/update_branch.go
  server/update_branch_test.go
Labels: 3: Reviews Complete

#207 MM-27373: Ignore comments coming from issues
  server/server.go
Labels: 3: Reviews Complete

#203 server: fix a regression introduced in #186
  server/github_pr.go
  server/server.go
Labels: 3: Reviews Complete

#205 server: fix gh issue service error if there isnt repo field in issue
  server/github.go
  server/issue_handler_test.go
Labels: 2: Dev Review

#208 Expose /metrics endpoint to be scraped later on
  Dockerfile
  Tiltfile
  config/config-mattermod.default.json
  deploy/base/app/deployment.yaml
  deploy/base/app/service.yaml
Labels: 2: Dev Review

#210 Include error object in the error log for checkpractivity
  server/pull_request.go
Labels: 2: Dev Review
