Repository mattermost/mattermost-mattermod, pull requests merged in 2020-10, with the labels that each got.

#246 [MM-29076] Send welcome message for community PRs
  config/config-mattermod.default.json
  server/cla.go
  server/cla_test.go
  server/community.go
  server/community_test.go
  server/config.go
  server/issue_comment_handler.go
  server/pull_request_handler.go
Labels: 3: Reviews Complete

#247 MM-28978 Move away from gorp to sqlx in issue_store.go
  model/issue.go
  model/string_array.go
  store/sql_issue_store.go
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#249 Add 'hacktoberfest-accepted' label instead of 'hacktoberfest' label in PRs
  server/community.go
Labels: 3: Reviews Complete

#250 Temporary reduce prod replicas to 1 due to pvc issue
  deploy/overlays/prod/kustomization.yaml
Labels: 2: Dev Review

#252 15568 move-away-from-gorp-to-sqlx-in-pull_request_store
  go.mod
  model/pull_request.go
  store/sql_issue_store_test.go
  store/sql_pull_request_store.go
  store/sql_pull_request_store_test.go
  store/sql_store.go
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted
